### PR TITLE
OUPDAUNTLE-55 remove solr4 support and update gradle

### PR DESCRIPTION
**Pull request by hechmi-dammak-xenit**

### CODE REVIEW

**Review by thijslemmens — COMMENTED** [review]
Will this work with SSL enabled?

**Comment by hechmi-dammak-xenit** [comment]
> Will this work with SSL enabled?

it's an endpoint that is part of a RequestHandlerBase , so yes it will.

**Comment by thijslemmens** [comment]
> > Will this work with SSL enabled?
> 
> it's an endpoint that is part of a RequestHandlerBase , so yes it will.

I'm not convinced. You will need to add a client certificate and truststore to do a simple health check, won't you?

**Comment by hechmi-dammak** [comment]
> > > Will this work with SSL enabled?
> > 
> > 
> > it's an endpoint that is part of a RequestHandlerBase , so yes it will.
> 
> I'm not convinced. You will need to add a client certificate and truststore to do a simple health check, won't you?

yes same as querying solr for anything else

**Comment by thijslemmens** [comment]
> > > > Will this work with SSL enabled?
> > > 
> > > 
> > > it's an endpoint that is part of a RequestHandlerBase , so yes it will.
> > 
> > 
> > I'm not convinced. You will need to add a client certificate and truststore to do a simple health check, won't you?
> 
> yes same as querying solr for anything else

So how can it work in practice?

**Review by thijslemmens — COMMENTED** [review]
Don't leak client tickets in public PR's and commits.

**Review by thijslemmens — APPROVED** [review]

**Pull request closed without merging**
